# GitHub Actions workflow: Deploy to AWS with agentstr-cli

name: deploy-aws

# Trigger manually or when the AWS config changes
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "configs/aws.yml"
      - ".github/workflows/deploy-aws.yml"

env: 
  AGENTSTR_PROVIDER: aws
  AGENTSTR_CONFIG: configs/aws.yml  # Change this to your config file

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: uv run agentstr deploy -f configs/aws.yml
