# Sample Azure configuration for agentstr CLI (Azure Container Instances)
provider: azure

azure:
  subscription_id: c74e33bd-a84b-42e0-8993-ebc4cfbb76a3  # replace with your subscription ID
  region: eastus
  resource_group: agentstr-rg
  acr_name: agentstr              # Azure Container Registry (must exist or will be created)
  cpu: 1                          # integer cores (ACI requirement)
  memory_gb: 0.5                  # GB
  restart_policy: OnFailure

image:
  repository: mcp-server
  build_context: .
  extra_pip_deps: []

env:
  NOSTR_RELAYS: >
    wss://relay.primal.net,wss://relay.damus.io,wss://nostr.mom

secrets:                          # plaintext here or reference a Key Vault secret URI
  EXAMPLE_MCP_SERVER_NSEC: nsec1rcskcnejy8k65jhxkpva9lcqln9eyw2r50auwd7a0kydy47azpwss25v24
  MCP_SERVER_NWC_CONN_STR: nostr+walletconnect://aa179666fd6aa18def568acf6f9fa7d39195
