# Sample GCP configuration for agentstr CLI (GKE)
provider: gcp

file_path: examples/commands_server.py

database: true  # Provision postgres database

extra_pip_deps:  # Additional Python deps installed in image
  - agentstr-sdk==0.4.13

env:  # Environment Variables
  NOSTR_RELAYS: wss://relay.primal.net,wss://relay.damus.io,wss://nostr.mom

secrets: # Secret Manager paths (latest version)
  MCP_SERVER_NSEC: projects/agentstr/secrets/MCP_SERVER_NSEC/versions/latest
  MCP_SERVER_NWC_CONN_STR: projects/agentstr/secrets/MCP_SERVER_NWC_CONN_STR/versions/latest
  MCP_SERVER_PUBKEY: projects/agentstr/secrets/MCP_SERVER_PUBKEY/versions/latest
