name: nostr-agent-tools-ci
on:
  push:
    branches:
      - '**'

# Grant write permissions so the action can push commits back
permissions:
  contents: write
jobs:
  uv-example:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Bump patch version
        run: python .github/scripts/bump_patch.py

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Start agentstr relay
        run: |
          uv run agentstr relay run &
          echo $! > relay.pid
        shell: bash

      - name: Wait for relay to become ready
        run: sleep 5

      - name: Run unit tests
        run: uv run pytest tests/
        env:
          TEST_NWC_CONN_STR: ${{ secrets.TEST_NWC_CONN_STR }}

      - name: Stop agentstr relay
        if: always()
        run: kill $(cat relay.pid)

      - name: Build
        run: uv build

      - name: Commit bumped version
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): bump patch version [skip ci]"
          file_pattern: pyproject.toml

      - name: Publish to PyPI
        if: github.ref == 'refs/heads/main'
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}