# GitHub Actions workflow: Deploy to Azure Container Instances with agentstr-cli

name: deploy-azure

on:
  workflow_dispatch:
  push:
    paths:
      - "configs/azure.yml"
      - ".github/workflows/deploy-azure.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install agentstr-cli
        run: |
          python -m pip install --upgrade pip
          pip install "agentstr-sdk[cli]"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: agentstr-cli deploy -f configs/azure.yml
