# GitHub Actions workflow: Deploy to Google Cloud Run with agentstr-cli

name: deploy-gcp

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "configs/gcp.yml"
      - ".github/workflows/deploy-gcp.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Bump patch version
        run: python .github/scripts/bump_patch.py

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to GCP
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: agentstr-cli deploy -f configs/gcp.yml
