# GitHub Actions workflow: Deploy to Azure Container Instances with agentstr-cli

name: deploy-azure

on:
  workflow_dispatch:
  push:
    #branches:
    #  - main
    paths:
      - "configs/azure.yml"
      - ".github/workflows/deploy-azure.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: uv run agentstr deploy -f configs/azure.yml
